### ISSUE TITLE
 Get rid of IE8 and 9 compatibility for Geotrek v2 ?

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-rando#286]
I'm really wondering which browser compatibility we should target for the new version of Geotrek Rando.

On one hand if we decide to go forward, it could be interesting to leave IE 8 and 9 and focus on using new layout technics more efficient and easily adjustable.

To give an insight about this statement, IE8 is almost dead. Most of the upcoming frameworks CMS and interesting technologies have made the choice of leaving it behind.
It's a little bit more blurry about IE9 as people with old Windows Vista can still have it, but people with more recents platforms have seen their IE upgrading at least to 10.
With this the announce of Microsoft releasing a new browser soon, I think we should let those old guys on the side of the road :)

Here are the main pros and cons :
### PROS :
* allows us to use real grid systems like flex-box in css
* allow us to code cross-browser code easily without huge frameworks
* is definitely a step toward future instead of compensating for ie past mistakes

### CONS :
* We let some potentials or currents targets aside

@camillemonchicourt, I really would like to know what you think about this and if you have some stats about the audience of Geotrek on your server, it would be of a great help to rationalize this decision.
Also @leplatrem if you have an opinion as it's still a bit your baby, it would be one more voice to bring arguments.

Thx guys !

**Comment by amandine-sahl** [comment]
If we refer to our website consultation. 11% of users use IE and in those 11% : 
 89% : IE11
 10% : IE 10

**Comment by camillemonchicourt** [comment]
Yes, interesting point. 
So here are some stats about RANDO ECRINS users : 

**From December 2014 to January 2015 : **

5.392 visitors / 12.927 pages views / 2,4 pages by session / 3 min average for each session.
Desktop : 78% / Tablet : 11% / Mobile : 11%

**BROWSERS**

- Chrome : 39,6%
Only recent versions (Versions 39 represent more than 85%)
- Firefox : 30,5% - Version 30 and + represent more than 90%
- Safari : 13,6%
- Internet explorer : 11,80% - Version11 : 50,4% / v9 : 22,8% / v8 : 20,4% / v10 : 5% / v7 : 1,1% / v6 : 0,16%

It means IE8 represent 2,4% of users and IE9 represent 2,6% of users. 
275 sessions from December 2014 to yesterday.

Lucky us, it is better than in 2013 (https://github.com/makinacorpus/Geotrek-rando/issues/16) :-)

**OS**

Windows : 69% / Mac : 9,8% / Android : 9% / iOS : 8,7% / Linux : 2,8% / Windows phone : 0,26%

**Screen Resolutions**

- 1366x768 : 16,6%
- 1920x1080 : 11,2%
- 1600x900 : 9,2%
- 1280x800 : 8,5%
- 1280x1024 : 6,8%
- 1680x1050 : 6,5%
- 1440x900 : 6,4%
- 768x1024 : 5,8%
- 1024x768 : 3,9%
- 1920x1200 : 3,6%

**Additional details :**

103 562 visitors since July 9th, 2013 (laucnhing) which makes 184 visitors/day average.
500 to 700 visitors each day in July and August 2014

France : 86% / Belgium : 3% / Spain : 1,3% / Italy : 1,3% / Netherlands : 1,2% / Switzerland : 1% / Germany : 0,9% / UK : 0,6% / USA : 0,5% / Canada : 0,5% / ....

**Comment by camillemonchicourt** [comment]
@amandine-sahl, I can't trust people are moderner in Cevennes !!! :-p

On, our website in January 2015 : 

IE = 17,5 % of sessions

IE11 : 63,3 %
IE9 : 16 %
IE8 : 9,4 %
IE10 : 8,1 %
IE7 : 3 %
IE6 : 0,1 %

**Comment by leplatrem** [comment]
My opinion hasn't changed : if you take care of old buggy browsers, users do not upgrade them.

I would definitely drop IE8 and IE9, and target the effort on neat modern features.

**Comment by SBats** [comment]
Thanks a lot for those stats @amandine-sahl and @camillemonchicourt ! And thx for your feedback @leplatrem (even if I was quite sure about your answer :D).
Really interesting in fact. We've got something like 2% of IE9 users and 1% of IE8 for ECRINS and not at all for Cevennes.
In my opinion, we really should ignore those 3%. It will definitely be a step forward and a very small loss. Of course we would put a kind of warning on the site for people with old browsers, asking them to change or upgrade these.

Regarding those informations, do you have any objection Amandine and Camille ?

**Comment by camillemonchicourt** [comment]
@leplatrem, I dont think that if the website dont work they will understand that they have to upload their browser. They will rather think "Very bad website!".

With a WARNING it will work.

We have 5% here but we agree that we can ignore them and guess that they will be even less in the coming months. So it would be a bad to dont use some features adn technologies or to develop heavy things for a few users thet will disappear soon. 

Good to go!

**Comment by leplatrem** [comment]
Yes of course, the warning is a common pattern!

Ideally, implementing a full content adaptation is the best approach. But who is willing to pay for that ? :) It's already quite a hard job to target every (even modern) platform! http://andregarzia.com/posts/en/whatsappdoesntunderstandtheweb/ :)

**Comment by SBats** [comment]
Ok guys, thank you for your time about this point. We all agree about letting IE 8 and 9 compatibility aside. We'll set up a warning for old browsers and focus on current and future gen browsers.
