### ISSUE TITLE
Synchro VS API - Question

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-rando#304]
In Geotrek-rando V1 datas were published by a synchronisation that pulled files from Geotrek-admin database to Geotrek-rando (images, trek.geojson, poi.geojson, pdf, dem.json, profile.svg, ....).

In V2, it now works with an API and Geotrek-rando gets datas direct from Geotrek-admin using this API. 
But isnt it a lot slower and louder as it sends requests to Geotrek-admin database each time ?
And the PDF exports has to be generated each time a visitor ask for it ?

What about security for Geotrek-admin and for datas ?

Thanks.

**Comment by gutard** [comment]
Yes, we designed Geotrek-Rando v2 to be full js and to be able to use Geotrek-Admin API directly. The idea is to require only a static web server on Geotrek-Admin. This allows to host it on a shared hosting or a CDN. However we plan to add the possibility to make a static copy of data on Geotrek-Rando server for performance and security.

**Comment by leplatrem** [comment]
As long as server-side caching is well setup, Geotrek-Rando can fetch the content from there without much problems.

However if any of the public endpoint is not well cached, it could disturb the daily work of employees on Geotrek-admin.

And caching is hard.

One idea would be to put a static caching tool like Varnish in front of Geotrek public APIs...

Anyway, since you designed the first sync mecanism, I'm sure you're full of brainwaves :)

**Comment by camillemonchicourt** [comment]
OK thanks for these details. 
And it seems to be necessary to have a copy on Geotrek-Rando server.

**Comment by leplatrem** [comment]
> And it seems to be necessary to have a copy on Geotrek-Rando server. 
> 

A static copy must be built for the mobile app too, so we could maybe imagine that Rando would consume the same archive (*or an extracted version in a static folder*)
